/**
 * O que o cliente revisa: cada página do site e as seções que ela tem, na ordem em que
 * aparecem, pelo título que se lê na tela.
 *
 * É este arquivo que adapta a ferramenta para outro projeto — a página de revisão, a rota de
 * registro e os componentes não sabem nada sobre a The Dark Film. Trocar esta lista basta.
 *
 * Os `id` são a chave dos eventos registrados. **Nunca renomeie um id de página ou seção que
 * já esteja em uso**: o histórico de aprovação está amarrado a ele. Mudar o `titulo` é livre.
 */

export type SecaoRevisao = { id: string; titulo: string };

export type PaginaRevisao = {
  id: string;
  titulo: string;
  /** Caminho no site, aberto em nova aba a partir da revisão. */
  href: string;
  grupo: string;
  /** Uma frase curta sobre o que a pessoa deve olhar naquela página. */
  nota?: string;
  secoes: SecaoRevisao[];
};

export const paginasRevisao: PaginaRevisao[] = [
  {
    id: "home",
    titulo: "Home",
    href: "/",
    grupo: "Páginas do site",
    secoes: [
      { id: "pelicula-som-e-acessorios-com-34-anos-de-estrada", titulo: "Película, som e acessórios com 34 anos de estrada." },
      { id: "tres-especialidades-uma-oficina", titulo: "Três especialidades, uma oficina." },
      { id: "veja-a-tonalidade-antes-de-aplicar", titulo: "Veja a tonalidade antes de aplicar." },
      { id: "aplicadora-credenciada-3m", titulo: "Aplicadora credenciada 3M." },
      { id: "nossa-qualidade-e-atestada-pelo-servico-prestado", titulo: "Nossa qualidade é atestada pelo serviço prestado aos clientes." },
      { id: "na-oficina", titulo: "Na oficina" },
      { id: "som-e-a-outra-metade-do-nome", titulo: "Som é a outra metade do nome" },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "a-empresa",
    titulo: "A Empresa",
    href: "/a-empresa",
    grupo: "Páginas do site",
    secoes: [
      { id: "a-mais-experiente-e-reconhecida-da-regiao", titulo: "A mais experiente e reconhecida da região." },
      { id: "desde-1992-anos-de-mercado-e-credencial", titulo: "Desde 1992, anos de mercado e credencial" },
      { id: "de-1992-ate-hoje", titulo: "De 1992 até hoje." },
      { id: "qualidade-e-rapidez-buscando-sempre-a-satisfacao", titulo: "Qualidade e rapidez, buscando sempre a satisfação total do cliente." },
      { id: "nossa-qualidade-e-atestada-pelo-servico-prestado", titulo: "Nossa qualidade é atestada pelo serviço prestado aos clientes." },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "peliculas-automotivas",
    titulo: "Películas Automotivas",
    href: "/peliculas-automotivas",
    grupo: "Páginas do site",
    secoes: [
      { id: "aplicacao-perfeita-sem-emendas", titulo: "Aplicação perfeita, sem emendas." },
      { id: "os-unicos-em-petropolis-com-chancela-abrawf", titulo: "Os únicos em Petrópolis com chancela ABRAWF." },
      { id: "simule-a-sua-pelicula", titulo: "Simule a sua película." },
      { id: "pelicula-automotiva-de-protecao-e-seguranca", titulo: "Película automotiva de proteção e segurança." },
      { id: "mais-para-o-seu-carro", titulo: "Mais para o seu carro" },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "peliculas-arquitetonicas",
    titulo: "Películas Arquitetônicas",
    href: "/peliculas-arquitetonicas",
    grupo: "Páginas do site",
    secoes: [
      { id: "solucao-atrativa-e-eficiente", titulo: "Solução atrativa e eficiente." },
      { id: "o-vidro-quebra-o-film-segura", titulo: "O vidro quebra, o film segura." },
      { id: "ver-sem-ser-visto", titulo: "Ver sem ser visto." },
      { id: "reducao-dos-custos-de-refrigeracao", titulo: "Redução dos custos de refrigeração." },
      { id: "aparencia-adequada-e-decoracao-de-interiores", titulo: "Aparência adequada e decoração de interiores." },
      { id: "peliculas-arquitetonicas-produtos", titulo: "Películas arquitetônicas (produtos)" },
      { id: "continue-por-aqui", titulo: "Continue por aqui" },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "caracteristicas-do-film",
    titulo: "Características do Film",
    href: "/caracteristicas-do-film",
    grupo: "Páginas do site",
    secoes: [
      { id: "o-que-e-film-afinal", titulo: "O que é film, afinal?" },
      { id: "dividido-nas-seguintes-categorias", titulo: "Dividido nas seguintes categorias:" },
      { id: "conforto-seguranca-e-economia", titulo: "Conforto, segurança e economia." },
      { id: "economico-ou-profissional-garantia", titulo: "Econômico ou profissional. (garantia)" },
      { id: "onde-aplicar", titulo: "Onde aplicar" },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "3m",
    titulo: "Credenciada 3M",
    href: "/3m",
    grupo: "Páginas do site",
    secoes: [
      { id: "menos-calor-mais-protecao", titulo: "Menos calor. Mais proteção." },
      { id: "por-que-3m", titulo: "Por que 3M" },
      { id: "cinco-peliculas-cinco-propositos", titulo: "Cinco películas, cinco propósitos." },
      { id: "lado-a-lado-comparativo", titulo: "Lado a lado. (comparativo)" },
      { id: "veja-a-3m-aplicada", titulo: "Veja a 3M aplicada" },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "legislacao",
    titulo: "Legislação",
    href: "/simulador",
    grupo: "Páginas do site",
    secoes: [
      { id: "veja-a-tonalidade-antes-de-aplicar", titulo: "Veja a tonalidade antes de aplicar." },
      { id: "qual-vidro-voce-quer-consultar-o-que-a-lei-permi", titulo: "Qual vidro você quer consultar? / O que a lei permite" },
      { id: "o-que-o-numero-da-pelicula-significa", titulo: "O que o número da película significa." },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "som-e-acessorios",
    titulo: "Som e Acessórios",
    href: "/som-e-acessorios",
    grupo: "Páginas do site",
    secoes: [
      { id: "nacionais-e-importados-tudo-em-um-lugar", titulo: "Nacionais e importados, tudo em um lugar." },
      { id: "escolha-o-grupo-ou-busque-catalogo", titulo: "Escolha o grupo ou busque. (catálogo)" },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "galeria",
    titulo: "Galeria",
    href: "/galeria",
    grupo: "Páginas do site",
    secoes: [
      { id: "trabalhos-de-verdade", titulo: "Trabalhos de verdade." },
      { id: "carros-que-passam-por-aqui", titulo: "Carros que passam por aqui" },
      { id: "aplicacao-de-pelicula-em-carros", titulo: "Aplicação de película em carros" },
      { id: "envelopamento", titulo: "Envelopamento" },
      { id: "multimidia-e-acessorios", titulo: "Multimídia e acessórios" },
      { id: "pelicula-arquitetonica", titulo: "Película arquitetônica" },
      { id: "a-loja", titulo: "A loja" },
      { id: "o-que-fazemos", titulo: "O que fazemos" },
      { id: "venha-nos-fazer-uma-visita", titulo: "Venha nos fazer uma visita." },
    ],
  },
  {
    id: "contato",
    titulo: "Contato",
    href: "/contato",
    grupo: "Páginas do site",
    secoes: [
      { id: "fale-com-a-gente", titulo: "Fale com a gente." },
      { id: "envie-sua-mensagem-formulario", titulo: "Envie sua mensagem. (formulário)" },
      { id: "ou-chame-direto-telefones-e-whatsapp", titulo: "Ou chame direto. (telefones e WhatsApp)" },
      { id: "onde-estamos-endereco-e-mapa", titulo: "Onde estamos (endereço e mapa)" },
    ],
  },
  {
    id: "produto-envelopamento-automotivo",
    titulo: "Envelopamento Automotivo",
    href: "/produtos/envelopamento-automotivo",
    grupo: "Produtos — Películas Automotivas",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-nao-troque-seu-parabrisa-conserte",
    titulo: "Não troque seu para-brisa, conserte!",
    href: "/produtos/nao-troque-seu-parabrisa-conserte",
    grupo: "Produtos — Películas Automotivas",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-distribuicao-de-peliculas-ferramentas-para-aplicadores-e-chancelas",
    titulo: "Distribuição de películas / ferramentas para aplicadores e chancelas",
    href: "/produtos/distribuicao-de-peliculas-ferramentas-para-aplicadores-e-chancelas",
    grupo: "Produtos — Películas Arquitetônicas",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-pelicula-comercial",
    titulo: "Película Comercial",
    href: "/produtos/pelicula-comercial",
    grupo: "Produtos — Películas Arquitetônicas",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-acessorios-automotivos-bepo",
    titulo: "Acessórios Automotivos BEPO",
    href: "/produtos/acessorios-automotivos-bepo",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-acessorios-automotivos-tg-poli",
    titulo: "Acessórios Automotivos TG POLI",
    href: "/produtos/acessorios-automotivos-tg-poli",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-alarme-para-motocicletas-positron-duoblock",
    titulo: "Alarme para Motocicletas POSITRON DuoBlock",
    href: "/produtos/alarme-para-motocicletas-positron-duoblock",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-alarmes-automotivos-kostal",
    titulo: "Alarmes Automotivos KOSTAL",
    href: "/produtos/alarmes-automotivos-kostal",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-alarmes-automotivos-positron-px-fx",
    titulo: "Alarmes Automotivos POSITRON PX / FX",
    href: "/produtos/alarmes-automotivos-positron-px-fx",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-alarmes-automotivos-sistec",
    titulo: "Alarmes Automotivos SISTEC",
    href: "/produtos/alarmes-automotivos-sistec",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-amplificadores-de-potencia",
    titulo: "Amplificadores de Potência",
    href: "/produtos/amplificadores-de-potencia",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-antenas",
    titulo: "Antenas",
    href: "/produtos/antenas",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-auto-falantes-triaxiais",
    titulo: "Auto-falantes Triaxiais",
    href: "/produtos/auto-falantes-triaxiais",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-auto-radio-usb-bluetooth",
    titulo: "Auto-rádio USB / Bluetooth",
    href: "/produtos/auto-radio-usb-bluetooth",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-bagageiros-e-racks",
    titulo: "Bagageiros e racks",
    href: "/produtos/bagageiros-e-racks",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-baterias-moura",
    titulo: "Baterias Moura",
    href: "/produtos/baterias-moura",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-bazookas-regency",
    titulo: "Bazookas REGENCY",
    href: "/produtos/bazookas-regency",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-buzina-caracol",
    titulo: "Buzina Caracol",
    href: "/produtos/buzina-caracol",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-buzinas-esportivas",
    titulo: "Buzinas Esportivas",
    href: "/produtos/buzinas-esportivas",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-caixas-seladas-regency",
    titulo: "Caixas Seladas REGENCY",
    href: "/produtos/caixas-seladas-regency",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-cameras-de-re",
    titulo: "Câmeras de Ré",
    href: "/produtos/cameras-de-re",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-capas-para-estepe",
    titulo: "Capas para Estepe",
    href: "/produtos/capas-para-estepe",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-capotas-maritimas",
    titulo: "Capotas maritimas",
    href: "/produtos/capotas-maritimas",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-engates-dhf",
    titulo: "Engates DHF",
    href: "/produtos/engates-dhf",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-engates-enforth",
    titulo: "Engates Enforth",
    href: "/produtos/engates-enforth",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-farois-auxiliares",
    titulo: "Faróis Auxiliares",
    href: "/produtos/farois-auxiliares",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-farois-de-led",
    titulo: "Faróis de Led",
    href: "/produtos/farois-de-led",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-filtro-de-ar-esportivo",
    titulo: "Filtro de ar esportivo",
    href: "/produtos/filtro-de-ar-esportivo",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-gps-navegador-portatil",
    titulo: "GPS - Navegador Portátil",
    href: "/produtos/gps-navegador-portatil",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-kit-duas-vias",
    titulo: "Kit Duas Vias",
    href: "/produtos/kit-duas-vias",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-kits-multimidia",
    titulo: "Kits Multimídia",
    href: "/produtos/kits-multimidia",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-lampadas-blue-vision-philips",
    titulo: "Lâmpadas Blue Vision PHILIPS",
    href: "/produtos/lampadas-blue-vision-philips",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-lampadas-crystal-vision-philips",
    titulo: "Lâmpadas Crystal Vision PHILIPS",
    href: "/produtos/lampadas-crystal-vision-philips",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-lampadas-xenon-6000k-8000k",
    titulo: "Lâmpadas Xenon 6000K / 8000K",
    href: "/produtos/lampadas-xenon-6000k-8000k",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-linha-de-personalizacao-shutt",
    titulo: "Linha de personalização SHUTT",
    href: "/produtos/linha-de-personalizacao-shutt",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-manometros",
    titulo: "Manômetros",
    href: "/produtos/manometros",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-modulos-de-levantamento-de-vidros-anti-esmagamento",
    titulo: "Módulos de levantamento de vidros anti-esmagamento",
    href: "/produtos/modulos-de-levantamento-de-vidros-anti-esmagamento",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-palhetas-para-limpador-de-parabrisas",
    titulo: "Palhetas para Limpador de Parabrisas",
    href: "/produtos/palhetas-para-limpador-de-parabrisas",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-protetores-de-carter",
    titulo: "Protetores de Carter",
    href: "/produtos/protetores-de-carter",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-receptor-de-tv-digital-automotivo",
    titulo: "Receptor de TV Digital Automotivo",
    href: "/produtos/receptor-de-tv-digital-automotivo",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-rodas-e-pneus-esportivos",
    titulo: "Rodas e Pneus Esportivos",
    href: "/produtos/rodas-e-pneus-esportivos",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-sensor-de-estacionamento",
    titulo: "Sensor de Estacionamento",
    href: "/produtos/sensor-de-estacionamento",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-subwoofer",
    titulo: "Subwoofer",
    href: "/produtos/subwoofer",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-tapetes-borcol",
    titulo: "Tapetes BORCOL",
    href: "/produtos/tapetes-borcol",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
  {
    id: "produto-vidros-e-travas-eletricas",
    titulo: "Vidros e travas elétricas",
    href: "/produtos/vidros-e-travas-eletricas",
    grupo: "Produtos — Som e Acessórios",
    secoes: [{ id: "pagina", titulo: "Texto, fotos e tudo o que estiver nesta página" }],
  },
];
